version: '3'

services:
    pandoc:
        image: jagregory/pandoc
        volumes:
          - ./:/source
        command: -s --toc manual/MANUAL.md -o docs/index.html

    docs:
        image: asciidoctor/docker-asciidoctor

        volumes:
        - ./manual:/documents
        - ./docs:/html

        command: asciidoctor -o /html/index.html MANUAL.adoc -a TLP_STRESS_VERSION=${TLP_STRESS_VERSION}

