# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

aliases:
  base_job: &base_job
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

commands:
  install_ccm:
    description: "Installs and starts CCM"
    parameters:
      version:
        type: string
        default: "2.2.14"
      cluster_name:
        type: string
        default: "test"

    steps:
      - restore_cache:
          keys:
            - ccm

      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
      - run: sudo pip install pyYaml ccm
      - run: ccm create test -n 3 -v << parameters.version >>
      - run:
          name: "Adjust cluster parameters"
          command: |
            for i in `seq 1 1` ; do
              sed -i 's/#MAX_HEAP_SIZE="4G"/MAX_HEAP_SIZE="256m"/' ~/.ccm/test/node$i/conf/cassandra-env.sh
              sed -i 's/#HEAP_NEWSIZE="800M"/HEAP_NEWSIZE="128m"/' ~/.ccm/test/node$i/conf/cassandra-env.sh
              sed -i 's/num_tokens: 256/num_tokens: 1/' ~/.ccm/test/node$i/conf/cassandra.yaml
              echo 'phi_convict_threshold: 16' >> ~/.ccm/test/node$i/conf/cassandra.yaml
              sed -i 's/concurrent_reads: 32/concurrent_reads: 4/' ~/.ccm/test/node$i/conf/cassandra.yaml
              sed -i 's/concurrent_writes: 32/concurrent_writes: 4/' ~/.ccm/test/node$i/conf/cassandra.yaml
              sed -i 's/concurrent_counter_writes: 32/concurrent_counter_writes: 4/' ~/.ccm/test/node$i/conf/cassandra.yaml
              sed -i 's/# file_cache_size_in_mb: 512/file_cache_size_in_mb: 1/' ~/.ccm/test/node$i/conf/cassandra.yaml
              sed -i 's/enable_materialized_views: false/enable_materialized_views: true/' ~/.ccm/test/node$i/conf/cassandra.yaml
            done

      - run:
          name: "Run Tests"
          command: |
            ccm start -v
            sleep 5
            ccm status
            ccm checklogerror
            tail -n 50 /home/circleci/.ccm/test/node1/logs/system.log
            ./gradlew test --stacktrace

      - store_test_results:
          path: /home/circleci/repo/build/test-results

  gradle_test:
    description: "Run gradle test and deal with caches"
    steps:
      - restore_cache:
          keys:
            - gradle-deps-{{ checksum "build.gradle" }}
      - run: ./gradlew test -i
      - save_cache:
          key: gradle-deps-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/

  build_packages:
    description: "Build packages through gradle"
    steps:
      - run: ./gradlew buildAll

jobs:

  build:
    <<: *base_job

    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
      - run: sudo pip install pyYaml ccm

      - run:
          name: Download CCM for Cache
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
            sudo pip install pyYaml ccm
            ccm create cassandra_30 --no-switch -v 3.0.19
            ccm create cassandra_311 --no-switch -v 3.11.5

      - save_cache:
          key: ccm
          paths:
            - ~/.ccm/repository

      - run:
          name: "run I guess"
          command: ./gradlew testClasses

  cassandra_30:
    <<: *base_job

    steps:
      - checkout
      - install_ccm:
          version: 3.0.19

  cassandra_311:
    <<: *base_job

    steps:
      - checkout
      - install_ccm:
          version: 3.11.5

  build_packages:
    <<: *base_job

    steps:
      - checkout
      - build_packages

workflows:
  version: 2.1

  cassandra_30:
    jobs:
      - build
      - cassandra_30

  cassandra_311:
    jobs:
      - build
      - cassandra_311

  build_everything:
    jobs:
      - build_packages